Pages/ChangePassword.cshtml.cs
using System.ComponentModel.DataAnnotations;
using FreshFarmMarket.Models;
using FreshFarmMarket.Services;
using FreshFarmMarket.Util;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages;

[Authorize]
public class ChangePasswordModel : PageModel
{
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    private readonly PasswordHistoryValidator _phValidator;
    private readonly EventLogService<ChangePasswordModel> _logger;
    public ChangePasswordModel(UserManager<User> userManager, SignInManager<User> signInManager, PasswordHistoryValidator phValidator, EventLogService<ChangePasswordModel> logger)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _phValidator = phValidator;
        _logger = logger;
    }

    [BindProperty]
    [DataType(DataType.Password)]
    public string? NewPassword { get; set; }
    [BindProperty]
    [DataType(DataType.Password)]
    public string? OldPassword { get; set; }

    public async Task<IActionResult> OnGet()
    {
        var user = await _userManager.GetUserAsync(User);
        if (!await _phValidator.CanChangePassword(user))
        {
            return Redirect("/Index");
        }
        return Page();
    }

    public async Task<IActionResult> OnPost()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var user = await _userManager.GetUserAsync(User);
        var result = await _userManager.ChangePasswordAsync(user, OldPassword, NewPassword);
        if (result.Succeeded)
        {
            await _logger.Log(Event.CHANGE_PASSWORD, $"{user.UserName} changed password at {DateTime.Now}", user);
            await _phValidator.AddPasswordHash(user, _userManager.PasswordHasher.HashPassword(user, NewPassword));
            await _signInManager.SignOutAsync();
            return Redirect("/Login");
        }
        else
        {
            foreach (var err in result.Errors)
            {
                ModelState.AddModelError(nameof(NewPassword), err.Description);
            }
            return Page();
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Pages/ForgetPassword.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using FreshFarmMarket.Models;
using FreshFarmMarket.Services;
using FreshFarmMarket.Util;

namespace FreshFarmMarket.Pages;

public class ForgetPasswordModel : PageModel
{
    private readonly UserManager<User> _userManager;
    private readonly CommunicationService _communicationService;
    private readonly PasswordHistoryValidator _phValidator;
    private readonly EventLogService<ForgetPasswordModel> _logger;

    public ForgetPasswordModel(CommunicationService communicationService, UserManager<User> userManager, PasswordHistoryValidator phValidator, EventLogService<ForgetPasswordModel> logger)
    {
        _communicationService = communicationService;
        _userManager = userManager;
        _phValidator = phValidator;
        _logger = logger;
    }

    [BindProperty]
    public string? UserName { get; set; }

    [BindProperty]
    public string? PhoneNumber { get; set; }

    [BindProperty]
    public string? Code { get; set; }

    [BindProperty]
    public string? NewPassword { get; set; }
    public bool CodeSent { get; set; } = false;

    public async Task<IActionResult> OnPostSend()
    {
        if (UserName is null)
        {
            ModelState.AddModelError(nameof(UserName), "The UserName field is required.");
            return Page();
        }

        if (PhoneNumber is null)
        {
            ModelState.AddModelError(nameof(PhoneNumber), "The PhoneNumber field is required.");
            return Page();
        }

        var user = await _userManager.FindByNameAsync(UserName);

        if (user is null)
        {
            ModelState.AddModelError(nameof(UserName), "User with this username doesn't exist.");
            return Page();
        }

        if (user.PhoneNumber != PhoneNumber)
        {
            ModelState.AddModelError(nameof(PhoneNumber), "Wrong phone number.");
            return Page();
        }

        var code = await _userManager.GeneratePasswordResetTokenAsync(user);
        await _communicationService.SendSms(PhoneNumber, code);

        CodeSent = true;

        TempData["UserName"] = UserName;

        return Page();
    }

    public async Task<IActionResult> OnPostVerify()
    {
        if (NewPassword is null)
        {
            ModelState.AddModelError(nameof(NewPassword), "The NewPassword field is required.");
            return Page();
        }
        if (Code is null)
        {
            ModelState.AddModelError(nameof(Code), "The Code field is required.");
            return Page();
        }

        var user = await _userManager.FindByNameAsync(UserName);

        var result = await _userManager.ResetPasswordAsync(user, Code, NewPassword);

        if (result.Succeeded)
        {
            await _logger.Log(Event.FORGET_PASSWORD, $"{user.UserName} forget password at {DateTime.Now}", user);
            await _phValidator.AddPasswordHash(user, _userManager.PasswordHasher.HashPassword(user, NewPassword));
            return Redirect("/Login");
        }
        else
        {
            foreach (var err in result.Errors)
            {
                ModelState.AddModelError(nameof(NewPassword), err.Description);
            }
            return Page();
        }
    }
}

Pages/GetAdmin.cshtml.cs
using FreshFarmMarket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages;

[Authorize]
public class GetAdminModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly UserManager<User> _userManager;

    public GetAdminModel(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
    {
        _roleManager = roleManager;
        _userManager = userManager;
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (!await _roleManager.RoleExistsAsync("Admin"))
        {
            await _roleManager.CreateAsync(new()
            {
                Name = "Admin"
            });
        }
        await _userManager.AddToRoleAsync(user, "Admin");
        return Redirect("/Logs");
    }
}

Pages/GoogleLogin.cshtml.cs
using System.Security.Claims;
using FreshFarmMarket.Models;
using FreshFarmMarket.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages;

public class GoogleLogin : PageModel
{
    private readonly SignInManager<User> _signInManager;
    private readonly EventLogService<GoogleLogin> _logger;

    public GoogleLogin(SignInManager<User> signInManager, EventLogService<GoogleLogin> logger)
    {
        _signInManager = signInManager;
        _logger = logger;
    }

    public async Task<IActionResult> OnGet(bool isPersistent)
    {
        var loginInfo = await _signInManager.GetExternalLoginInfoAsync();
        var result = await _signInManager.ExternalLoginSignInAsync(loginInfo.LoginProvider, loginInfo.ProviderKey, isPersistent, true);

        if (result.Succeeded)
        {
            return Redirect("/Index");
        }

        var email = loginInfo.Principal.FindFirstValue(ClaimTypes.Email);
        if (email is not null)
        {
            var user = await _signInManager.UserManager.FindByEmailAsync(email);
            if (user is null)
            {
                // create user if not exist
                user = new User
                {
                    UserName = loginInfo.Principal.FindFirstValue(ClaimTypes.Email),
                    Email = loginInfo.Principal.FindFirstValue(ClaimTypes.Email),
                };
                await _signInManager.UserManager.CreateAsync(user);
                await _logger.Log(Event.EXTERNAL_REGISTER, $"{user.UserName} registered with external provider at {DateTime.Now}", user);
            }
            await _signInManager.UserManager.AddLoginAsync(user, loginInfo);
            await _signInManager.SignInAsync(user, isPersistent);
            await _logger.Log(Event.EXTERNAL_SIGNIN, $"{user.UserName} sign in with external provider at {DateTime.Now}", user);
        }
        return Redirect("/");
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages;

[Authorize]
public class IndexModel : PageModel
{
    public void OnGet()
    {

    }
}

Pages/Login.cshtml.cs
using System.ComponentModel.DataAnnotations;
using FreshFarmMarket.Models;
using FreshFarmMarket.Util;
using FreshFarmMarket.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Options;
using Microsoft.Net.Http.Headers;

namespace FreshFarmMarket.Pages;

public class LoginModel : PageModel
{
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    private readonly GoogleReCaptchaService _googleService;
    private readonly IOptions<GoogleReCaptchaConfig> _config;
    private readonly EventLogService<LoginModel> _logger;
    public LoginModel(SignInManager<User> signInManager, UserManager<User> userManager, IOptions<GoogleReCaptchaConfig> config, GoogleReCaptchaService googleService, EventLogService<LoginModel> logger)
    {
        _signInManager = signInManager;
        _userManager = userManager;
        _config = config;
        _googleService = googleService;
        _logger = logger;
    }

    [BindProperty]
    [Required]
    public string UserName { get; set; } = default!;

    [BindProperty]
    [DataType(DataType.Password)]
    [Required]
    public string Password { get; set; } = default!;

    [BindProperty]
    public bool RememberMe { get; set; }

    [BindProperty]
    public string Token { get; set; }

    public string GetSiteKey() => _config.Value.SiteKey;

    public IActionResult OnGet()
    {
        if (User?.Identity?.IsAuthenticated == true)
        {
            return Redirect("/Index");
        }
        return Page();
    }
    public IActionResult OnPostGoogle()
    {
        return Challenge(_signInManager.ConfigureExternalAuthenticationProperties("Google", "/GoogleLogin"), "Google");
    }
    public async Task<IActionResult> OnPostInHouse()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var success = await _googleService.Verify(Token);

        if (success == GoogleReCaptchaResult.FAIL)
        {
            return Page();
        }

        var user = await _userManager.FindByNameAsync(UserName);
        if (user is null)
        {
            ModelState.AddModelError(nameof(UserName), "Credentials are incorrect.");
            ModelState.AddModelError(nameof(Password), "Credentials are incorrect.");
            return Page();
        }

        var device = Request.Headers[HeaderNames.UserAgent].ToString();
        if (user.IsLoggedIn && await _userManager.CheckPasswordAsync(user, Password) && user.LastDevice != device)
        {
            ModelState.AddModelError(nameof(UserName), "User is already logged in another device.");
            return Page();
        }

        if (success == GoogleReCaptchaResult.SUSPICIOUS)
        {
            return RedirectToPage("/Verify/Tfa", new { RememberMe });
        }

        var result = await _signInManager.PasswordSignInAsync(user, Password, RememberMe, true);
        if (result.Succeeded)
        {
            await _logger.Log(Event.LOGIN, $"{user.UserName} logged in at {DateTime.Now}", user);
            if (!user.PhoneNumberConfirmed)
            {
                return Redirect("/Verify/Phone");
            }
            if (!user.EmailConfirmed)
            {
                return Redirect("/Verify/Email");
            }
            return Redirect("/Index");
        }
        else if (result.IsLockedOut)
        {
            return Redirect("/LockedOut");
        }
        else if (result.IsNotAllowed)
        {
            return Forbid();
        }
        else if (result.RequiresTwoFactor)
        {
            await _logger.Log(Event.LOGIN, $"{user.UserName} logged in at {DateTime.Now}", user);
            return RedirectToPage("/Verify/Tfa", new { RememberMe });
        }
        else
        {
            ModelState.AddModelError(nameof(UserName), "Credentials are incorrect.");
            ModelState.AddModelError(nameof(Password), "Credentials are incorrect.");
            return Page();
        }
    }
}

Pages/Logout.cshtml.cs
using FreshFarmMarket.Models;
using FreshFarmMarket.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages;

[Authorize]
public class LogoutModel : PageModel
{
    private readonly SignInManager<User> _signInManager;
    private readonly EventLogService<LogoutModel> _logger;

    public LogoutModel(SignInManager<User> signInManager, EventLogService<LogoutModel> logger)
    {
        _signInManager = signInManager;
        _logger = logger;
    }

    public async Task<IActionResult> OnGet()
    {
        var user = await _signInManager.UserManager.GetUserAsync(User);
        await _signInManager.SignOutAsync();
        HttpContext.Session.Clear();
        await _logger.Log(Event.LOGOUT, $"{user.UserName} logged out at {DateTime.Now}", user);
        if (user is not null)
        {
            user.IsLoggedIn = false;
            await _signInManager.UserManager.UpdateAsync(user);
        }
        return Redirect("/Login");
    }
}

Pages/Logs.cshtml.cs
using FreshFarmMarket.Data;
using FreshFarmMarket.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace FreshFarmMarket.Pages;

[Authorize(Roles = "Admin")]
public class LogsModel : PageModel
{
    private readonly DataContext _context;

    public LogsModel(DataContext context)
    {
        _context = context;
    }

    public List<EventLog> EventLogs { get; set; }

    public async Task OnGetAsync()
    {
        EventLogs = await _context.EventLogs
            .Include(e => e.User)
            .ToListAsync();
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FreshFarmMarket.Pages;

[Authorize]
public class PrivacyModel : PageModel
{
    public void OnGet()
    {
    }
}


Pages/ChangePassword.cshtml
@page
@model ChangePasswordModel

<main class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-6">
            <h1>Change Password</h1>
            <div asp-validation-summary="All" class="text-danger"></div>
            <form method="post" class="d-grid gap-3">
                <div class="form-group">
                    <label asp-for="NewPassword"></label>
                    <input placeholder="NewPassword" asp-for="NewPassword" class="form-control" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="OldPassword"></label>
                    <input placeholder="OldPassword" asp-for="OldPassword" class="form-control" />
                    <span asp-validation-for="OldPassword" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</main>

Pages/ForgetPassword.cshtml
@page
@model ForgetPasswordModel
@{
    var userName = TempData["UserName"] as string;
}

<main class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-6">
            <h1>Forget Password</h1>
            <div asp-validation-summary="All" class="text-danger"></div>
            <form method="post" class="d-grid gap-3" asp-page-handler="Send">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label asp-for="UserName">Username</label>
                    <input placeholder="UserName" asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber">PhoneNumber</label>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Send Code</button>
                @if (Model.CodeSent)
                {
                    <small class="text-muted">Sent!</small>
                }
            </form>
            @if (Model.CodeSent)
            {
                <form method="post" class="d-grid gap-3" asp-page-handler="Verify">
                    @Html.AntiForgeryToken()
                    <input type="hidden" asp-for="UserName" value="@userName">
                    <div class="form-group">
                        <label asp-for="Code"></label>
                        <input placeholder="Code" asp-for="Code" class="form-control" />
                        <span asp-validation-for="Code" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NewPassword"></label>
                        <input placeholder="NewPassword" asp-for="NewPassword" class="form-control" />
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">Reset</button>
                </form>
            }
        </div>
    </div>
</main>

Pages/GetAdmin.cshtml
@page
@model GetAdminModel;

<h1>Get Admin</h1>

Pages/GoogleLogin.cshtml
@page
@model GoogleLogin

Pages/Index.cshtml
@page
@model IndexModel
@using Microsoft.AspNetCore.Identity;
@using FreshFarmMarket.Models;
@inject UserManager<User> _userManager;
@{
    ViewData["Title"] = "Home page";
    var user = await _userManager.GetUserAsync(User);
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    @if (user is not null)
    {
        <hr>
        <h1 class="display-4">@user.UserName</h1>
        <p>@user.CreditCard</p>
        <p>@user.About</p>
        <p>@user.DeliveryAddress</p>
        <p>@user.Email</p>
        <p>@user.PhoneNumber</p>
        <p>@user.Gender</p>
        <img src="~/Uploads/@user.ImageFilePath">
    }
</div>

Pages/LockedOut.cshtml
@page

<h1>Yo ass is locked out fool</h1>
<small class="text-small">noob</small>

Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}

<main class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-6">
            <h1>Login</h1>
            <div asp-validation-summary="All" class="text-danger"></div>
            <form method="post" class="d-grid gap-3" asp-page-handler="InHouse">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label asp-for="UserName">Username</label>
                    <input placeholder="UserName" asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input placeholder="Password" asp-for="Password" class="form-control" />
                    <small><a asp-page="/ForgetPassword">Forgot password</a></small>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-check">
                    <input class="form-check-input" asp-for="RememberMe">
                    <label class="form-check-label" asp-for="RememberMe"></label>
                </div>
                <input type="hidden" asp-for="Token">
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <hr>
            <form method="post" class="d-grid gap-3" asp-page-handler="Google">
                <button type="submit" class="btn btn-primary">Google</button>
            </form>
        </div>
    </div>
</main>

<script src="https://www.google.com/recaptcha/api.js?render=@Model.GetSiteKey()"></script>
<script>
    setInterval(getToken(), 115000)

    function getToken() {
        grecaptcha.ready(function () {
            grecaptcha.execute('@Model.GetSiteKey()', { action: 'submit' }).then(function (token) {
                console.log(token)
                document.getElementById("Token").value = token
            });
        });
    }
</script>

Pages/Logout.cshtml
@page
@model LogoutModel

<h1>Bye!</h1>

Pages/Logs.cshtml
@page
@using FreshFarmMarket.Models;
@model LogsModel;

<h1>Logs</h1>
<ul>
    @foreach (EventLog log in Model.EventLogs)
    {
        <li>@log.Id || @log.Event || @(log.User?.UserName ?? "N/A") || @log.TimeStamp</li>
    }
</ul>

Pages/Register.cshtml
@page
@using FreshFarmMarket.Models
@model RegisterModel
@{
    ViewData["Title"] = "Register";
    var enumValues = Enum.GetValues(typeof(Gender)).Cast<Gender>();
    var selectList = new SelectList(enumValues);
}

<main class="container">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-6">
            <h1>Register</h1>
            <div asp-validation-summary="All" class="text-danger"></div>
            <form method="post" class="d-grid gap-3" enctype="multipart/form-data">
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <label asp-for="UserName">Username</label>
                    <input placeholder="UserName" asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input placeholder="Email" asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="form-label"></label>
                    <input placeholder="Image" asp-for="Image" class="form-control">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Gender"></label>
                    <select asp-for="Gender" asp-items="selectList" class="form-select"></select>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="About"></label>
                    <textarea asp-for="About" cols="30" rows="10" class="form-control"></textarea>
                    <span asp-validation-for="About" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PhoneNumber">Phone Number</label>
                    <input placeholder="PhoneNumber" asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreditCard">Credit Card Number</label>
                    <input placeholder="CreditCard" asp-for="CreditCard" class="form-control" />
                    <span asp-validation-for="CreditCard" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Street"></label>
                    <input placeholder="Street" asp-for="Street" class="form-control" />
                    <span asp-validation-for="Street" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PostalCode">Postal Code</label>
                    <input placeholder="PostalCode" asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <div class="small text-muted">Strength: <span id="strength"></span></div>
                    <div class="small text-muted">Guesses: <span id="guesses"></span></div>
                    <input placeholder="Password" asp-for="Password" class="form-control"
                        onchange="checkPasswordStrength()" onkeyup="checkPasswordStrength()" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword">Confirm Password</label>
                    <input placeholder="ConfirmPassword" asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Token">
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</main>


<script type="text/javascript" src="~/dist/zxcvbn.js"></script>
<script>
    const strengthSpan = document.getElementById("strength")
    const guessesSpan = document.getElementById("guesses")
    const passwordInput = document.getElementById("Password")
    const checkPasswordStrength = () => {
        var password = passwordInput.value
        var result = zxcvbn(password, user_inputs = [])

        // score: 0 to 4
        // guesses: number of tries
        let { score, guesses } = result

        if (score < 2) {
            strengthSpan.className = "text-danger"
            scoreText = "Weak"
        } else if (score <= 3) {
            strengthSpan.className = "text-warning"
            scoreText = "Okay"
        } else if (score == 4) {
            strengthSpan.className = "text-success"
            scoreText = "Good"
        }

        strengthSpan.innerText = scoreText
        guessesSpan.innerText = guesses

    }
</script>

<script src="https://www.google.com/recaptcha/api.js?render=@Model.GetSiteKey()"></script>
<script>
    setInterval(getToken(), 115000)

    function getToken() {
        grecaptcha.ready(function () {
            grecaptcha.execute('@Model.GetSiteKey()', { action: 'submit' }).then(function (token) {
                console.log(token)
                document.getElementById("Token").value = token
            });
        });
    }
</script>